baseURL = "https://pzzblog.netlify.app/"
languageCode = "zh-cn"
title = "pzzの博客"
theme = "zero"

[params]
  author = "KiritoBP"
  description = "一个使用 Hugo & PaperMod 搭建的博客"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  TocOpen = false
  defaultTheme = "auto" # 自动适配深色/浅色模式

[menu]
  [[menu.main]]
    identifier = "home"
    name = "🏠 首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tech"
    parent = "home"
    name = "tech"
    url = "/posts/tech/"
    weight = 1

  [[menu.main]]
    identifier = "ss2"
    parent = "home"
    name = "life"
    url = "/posts/life/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "📜 归档"
    url = "/archives/"
    weight = 2
    

  [[menu.main]]
    identifier = "about"
    name = "👤 关于"
    url = "/about/"
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"

  [markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2